import QuditClifford.AdjacentPauliNormality
import QuditClifford.AdjacentPresentedSymplectic

/-!
# The kernel of Pauli erasure in the adjacent presentation

The explicitly erased adjacent presentation is the quotient by the concrete
normal subgroup generated by scalar, X and Z circuit classes. The kernel is
identified by lifting guarded rewrites to this group quotient; no semantic
completeness or interpretation injectivity is used.
-/

noncomputable section
namespace QuditClifford.Circuit
variable {d n : ℕ} [NeZero d] [Fact d.Prime]
variable (g : (ZMod d)ˣ) [Fact (Odd d)] [Fact (orderOf g = d-1)]

/-- Every generator of the concrete Pauli subgroup is explicitly erased. -/
theorem adjacentPresentedPauliSubgroup_le_symplectic_ker :
    adjacentPresentedPauliSubgroup (n := n) g ≤ (adjacentPresentedToSymplectic g).ker := by
  apply (Subgroup.closure_le _).mpr
  intro p hp
  rcases hp with rfl | ⟨i, rfl | rfl⟩
  · change adjacentSymplecticClassWord g [.scalar] _ = 1
    simpa only [scalar, List.replicate_one] using
      adjacentSymplecticClassWord_scalar (n := n) g 1
  · change adjacentSymplecticClassWord g (X (d := d) i) _ = 1
    exact adjacentSymplecticClassWord_X g i
  · change adjacentSymplecticClassWord g (Z (d := d) i) _ = 1
    exact adjacentSymplecticClassWord_Z g i

private theorem adjacentSymplecticDerives_pauliQuotient_eq {u v : Word n}
    (hu : IsAdjacentWord u) (hv : IsAdjacentWord v) (h : AdjacentSymplecticDerives g u v) :
    QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) (adjacentClassWord g u hu) =
      QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) (adjacentClassWord g v hv) := by
  induction h with
  | refl w => rfl
  | @rule u v hr =>
    obtain ⟨hr, hua, hva⟩ := hr
    rcases hr with (hr | ⟨rfl, rfl⟩) | ⟨i, (rfl | rfl), rfl⟩
    · exact congrArg (QuotientGroup.mk' (adjacentPresentedPauliSubgroup g))
        ((adjacentClassWord_eq_iff_derives g u v hu hv).mpr (.rule ⟨hr, hua, hva⟩))
    · simpa only [adjacentClassWord_nil, map_one] using
        (QuotientGroup.eq_one_iff (adjacentClassWord (n := n) g [.scalar] hu)).mpr
          (scalar_mem_adjacentPresentedPauliSubgroup g)
    · simpa only [adjacentClassWord_nil, map_one] using
        (QuotientGroup.eq_one_iff (adjacentClassWord g (X (d := d) i) hu)).mpr
          (X_mem_adjacentPresentedPauliSubgroup g i)
    · simpa only [adjacentClassWord_nil, map_one] using
        (QuotientGroup.eq_one_iff (adjacentClassWord g (Z (d := d) i) hu)).mpr
          (Z_mem_adjacentPresentedPauliSubgroup g i)
  | symm h ih => exact (ih hv hu).symm
  | trans h₁ h₂ ih₁ ih₂ =>
    have hm := (AdjacentSymplecticDerives.isAdjacent_iff g h₁).mp hu
    exact (ih₁ hu hm).trans (ih₂ hm hv)
  | context l r h ih =>
    have hu' := (isAdjacentWord_append _ _).mp hu
    have hv' := (isAdjacentWord_append _ _).mp hv
    have hua := (isAdjacentWord_append _ _).mp hu'.1
    have hva := (isAdjacentWord_append _ _).mp hv'.1
    simp only [adjacentClassWord_append_certified, map_mul, ih hua.2 hva.2]

/-- Every explicitly erased adjacent class maps to the quotient by actual Pauli words. -/
def adjacentSymplecticToPauliQuotient :
    AdjacentPresentedSymplectic g n →*
      AdjacentPresentedCircuit g n ⧸ adjacentPresentedPauliSubgroup g where
  toFun := Quotient.lift
    (fun w => QuotientGroup.mk' (adjacentPresentedPauliSubgroup g)
      (adjacentClassWord g w.val w.property))
    (fun u v h => adjacentSymplecticDerives_pauliQuotient_eq g u.property v.property h)
  map_one' := rfl
  map_mul' := by
    intro a b
    obtain ⟨u, hu, rfl⟩ := adjacentSymplecticClassWord_exists g a
    obtain ⟨v, hv, rfl⟩ := adjacentSymplecticClassWord_exists g b
    change QuotientGroup.mk' (adjacentPresentedPauliSubgroup g)
        (adjacentClassWord g u hu * adjacentClassWord g v hv) =
      QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) (adjacentClassWord g u hu) *
        QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) (adjacentClassWord g v hv)
    exact (QuotientGroup.mk' (adjacentPresentedPauliSubgroup g)).map_mul _ _

@[simp] theorem adjacentSymplecticToPauliQuotient_classWord (w : Word n)
    (hw : IsAdjacentWord w) :
    adjacentSymplecticToPauliQuotient g (adjacentSymplecticClassWord g w hw) =
      QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) (adjacentClassWord g w hw) := rfl

@[simp] theorem adjacentSymplecticToPauliQuotient_presentedToSymplectic
    (p : AdjacentPresentedCircuit g n) :
    adjacentSymplecticToPauliQuotient g (adjacentPresentedToSymplectic g p) =
      QuotientGroup.mk' (adjacentPresentedPauliSubgroup g) p := by
  obtain ⟨w, hw, rfl⟩ := adjacentClassWord_exists g p
  rfl

/-- The kernel of guarded scalar/X/Z erasure is exactly their concrete normal subgroup. -/
theorem adjacentPresentedToSymplectic_ker_eq_adjacentPresentedPauliSubgroup :
    (adjacentPresentedToSymplectic (n := n) g).ker = adjacentPresentedPauliSubgroup g := by
  apply le_antisymm
  · intro p hp
    apply (QuotientGroup.eq_one_iff p).mp
    have h := congrArg (adjacentSymplecticToPauliQuotient g)
      (show adjacentPresentedToSymplectic g p = 1 from hp)
    simpa only [adjacentSymplecticToPauliQuotient_presentedToSymplectic, map_one] using h
  · exact adjacentPresentedPauliSubgroup_le_symplectic_ker g

/-- An erased adjacent derivation is precisely equality up to a concrete Pauli correction. -/
theorem adjacentSymplecticDerives_iff_pauli_correction (u v : Word n)
    (hu : IsAdjacentWord u) (hv : IsAdjacentWord v) :
    AdjacentSymplecticDerives g u v ↔ ∃ p ∈ adjacentPresentedPauliSubgroup g,
      adjacentClassWord g u hu = p * adjacentClassWord g v hv := by
  constructor
  · intro h
    have he := (adjacentSymplecticClassWord_eq_iff_derives g u v hu hv).mpr h
    refine ⟨adjacentClassWord g u hu * (adjacentClassWord g v hv)⁻¹, ?_, by group⟩
    rw [← adjacentPresentedToSymplectic_ker_eq_adjacentPresentedPauliSubgroup]
    change adjacentPresentedToSymplectic g
      (adjacentClassWord g u hu * (adjacentClassWord g v hv)⁻¹) = 1
    simp only [map_mul, map_inv, adjacentPresentedToSymplectic_classWord, he, mul_inv_cancel]
  · rintro ⟨p, hp, he⟩
    apply (adjacentSymplecticClassWord_eq_iff_derives g u v hu hv).mp
    have hp' : adjacentPresentedToSymplectic g p = 1 :=
      adjacentPresentedPauliSubgroup_le_symplectic_ker g hp
    have h := congrArg (adjacentPresentedToSymplectic g) he
    simpa only [map_mul, hp', one_mul, adjacentPresentedToSymplectic_classWord] using h

end QuditClifford.Circuit
