import QuditClifford.AdjacentPauliRewrites
import QuditClifford.AdjacentOneWireAlgebra
import QuditClifford.AdjacentExactNormal

/-!
# The concrete Pauli subgroup in the adjacent presentation is normal

The subgroup is generated by the exact scalar and expanded X/Z circuit
classes. Primitive conjugation is proved by restricted Pauli pushing and
structural interchange, then extended to arbitrary adjacent circuit words.
No semantic kernel or completeness assumption enters its definition or proof.
-/

noncomputable section
namespace QuditClifford.Circuit
variable {d n : ℕ} [NeZero d] [Fact d.Prime]
variable (g : (ZMod d)ˣ) [Fact (Odd d)] [Fact (orderOf g = d-1)]

private abbrev pg (a : Gate n) (ha : a.IsAdjacent) : AdjacentPresentedCircuit g n :=
  adjacentClassWord g [a] (by simpa using ha)

/-- The actual scalar and expanded Pauli generators in the source presentation. -/
def adjacentPresentedPauliGenerators : Set (AdjacentPresentedCircuit g n) :=
  {q | q = adjacentClassWord g [.scalar] (by simp) ∨
    ∃ i, q = adjacentClassWord g (X (d := d) i) (isAdjacentWord_X i) ∨
      q = adjacentClassWord g (Z (d := d) i) (isAdjacentWord_Z i)}

/-- The subgroup generated by scalar, X and Z classes, independently of semantics. -/
def adjacentPresentedPauliSubgroup : Subgroup (AdjacentPresentedCircuit g n) :=
  Subgroup.closure (adjacentPresentedPauliGenerators g)

theorem scalar_mem_adjacentPresentedPauliSubgroup :
    adjacentClassWord (n := n) g [.scalar] (by simp) ∈ adjacentPresentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inl rfl)

theorem X_mem_adjacentPresentedPauliSubgroup (i : Fin n) :
    adjacentClassWord g (X (d := d) i) (isAdjacentWord_X i) ∈ adjacentPresentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inr ⟨i, Or.inl rfl⟩)

theorem Z_mem_adjacentPresentedPauliSubgroup (i : Fin n) :
    adjacentClassWord g (Z (d := d) i) (isAdjacentWord_Z i) ∈ adjacentPresentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inr ⟨i, Or.inr rfl⟩)

theorem scalarWord_mem_adjacentPresentedPauliSubgroup (k : ℕ) :
    adjacentClassWord (n := n) g (scalar k) (isAdjacentWord_scalar k) ∈
      adjacentPresentedPauliSubgroup g := by
  simpa only [scalar, adjacentClassWord_replicate g .scalar Gate.isAdjacent_scalar] using
    (adjacentPresentedPauliSubgroup g).pow_mem (scalar_mem_adjacentPresentedPauliSubgroup g) k

theorem omegaPower_mem_adjacentPresentedPauliSubgroup (a : ZMod d) :
    adjacentClassWord (n := n) g (omegaPower a) (isAdjacentWord_omegaPower a) ∈
      adjacentPresentedPauliSubgroup g := scalarWord_mem_adjacentPresentedPauliSubgroup g _

private theorem flatten_mem (ws : List (Word n)) (hw : IsAdjacentWord ws.flatten)
    (h : ∀ w ∈ ws, ∀ hwa : IsAdjacentWord w,
      adjacentClassWord g w hwa ∈ adjacentPresentedPauliSubgroup g) :
    adjacentClassWord g ws.flatten hw ∈ adjacentPresentedPauliSubgroup g := by
  induction ws with
  | nil => exact (adjacentPresentedPauliSubgroup g).one_mem
  | cons w ws ih =>
    have ha := (isAdjacentWord_append w ws.flatten).mp hw
    simp only [List.flatten_cons, adjacentClassWord_append_certified]
    exact (adjacentPresentedPauliSubgroup g).mul_mem (h w (by simp) ha.1)
      (ih ha.2 (fun u hu hua => h u (by simp [hu]) hua))

theorem allX_mem_adjacentPresentedPauliSubgroup (x : Pauli.Basis d n) :
    adjacentClassWord g (allX x) (isAdjacentWord_allX x) ∈ adjacentPresentedPauliSubgroup g := by
  apply flatten_mem
  intro w hw hwa
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hw
  simpa only [Xexp, adjacentClassWord_power g (X i) (isAdjacentWord_X i)] using
    (adjacentPresentedPauliSubgroup g).pow_mem (X_mem_adjacentPresentedPauliSubgroup g i) (x i).val

theorem allZ_mem_adjacentPresentedPauliSubgroup (z : Pauli.Basis d n) :
    adjacentClassWord g (allZ z) (isAdjacentWord_allZ z) ∈ adjacentPresentedPauliSubgroup g := by
  apply flatten_mem
  intro w hw hwa
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hw
  simpa only [Zexp, adjacentClassWord_power g (Z i) (isAdjacentWord_Z i)] using
    (adjacentPresentedPauliSubgroup g).pow_mem (Z_mem_adjacentPresentedPauliSubgroup g i) (z i).val

theorem pauliWord_mem_adjacentPresentedPauliSubgroup (p : Pauli d n) :
    adjacentClassWord g (pauliWord p) (isAdjacentWord_pauliWord p) ∈
      adjacentPresentedPauliSubgroup g := by
  simp only [pauliWord, adjacentClassWord_append_certified]
  exact (adjacentPresentedPauliSubgroup g).mul_mem
    ((adjacentPresentedPauliSubgroup g).mul_mem (omegaPower_mem_adjacentPresentedPauliSubgroup g p.phase)
      (allX_mem_adjacentPresentedPauliSubgroup g p.x)) (allZ_mem_adjacentPresentedPauliSubgroup g p.z)

theorem signedPauliWord_mem_adjacentPresentedPauliSubgroup (p : SignedPauli d n) :
    adjacentClassWord g (signedPauliWord p) (isAdjacentWord_signedPauliWord p) ∈
      adjacentPresentedPauliSubgroup g := by
  simp only [signedPauliWord, adjacentClassWord_append_certified]
  exact (adjacentPresentedPauliSubgroup g).mul_mem (scalarWord_mem_adjacentPresentedPauliSubgroup g _)
    (pauliWord_mem_adjacentPresentedPauliSubgroup g p.2)

omit [Fact (Odd d)] [Fact (orderOf g = d-1)] in
private theorem gate_commute (a b : Gate n) (ha : a.IsAdjacent) (hb : b.IsAdjacent)
    (h : Disjoint a.support b.support) : Commute (pg g a ha) (pg g b hb) :=
  (adjacentClassWord_eq_iff_derives g _ _ (by simp [ha, hb]) (by simp [ha, hb])).mpr
    (adjacentDerives_disjoint g a b ha hb h)

set_option linter.unusedSectionVars false in
private theorem gate_commute_word (a : Gate n) (ha : a.IsAdjacent) (w : Word n)
    (hw : IsAdjacentWord w) (hs : ∀ b ∈ w, Disjoint a.support b.support) :
    Commute (pg g a ha) (adjacentClassWord g w hw) := by
  induction w with
  | nil => exact Commute.one_right _
  | cons b w ih =>
    obtain ⟨hb, hw⟩ := (isAdjacentWord_cons b w).mp hw
    change Commute (pg g a ha) (pg g b hb * adjacentClassWord g w hw)
    exact (gate_commute g a b ha hb (hs b (by simp))).mul_right
      (ih hw (fun c hc => hs c (by simp [hc])))

/-- A canonical primitive commutes with every expanded X on a disjoint wire. -/
theorem adjacentClassWord_gate_commute_X_of_not_mem (a : Gate n) (ha : a.IsAdjacent)
    (i : Fin n) (hi : i ∉ a.support) :
    Commute (adjacentClassWord g [a] (by simpa using ha))
      (adjacentClassWord g (X (d := d) i) (isAdjacentWord_X i)) := by
  apply gate_commute_word g a ha _ _
  intro b hb
  have hh : Disjoint a.support (Gate.H i).support := by simpa [Gate.support] using hi
  have hs : Disjoint a.support (Gate.S i).support := by simpa [Gate.support] using hi
  simp only [X, Sexp, List.mem_append, List.mem_cons, List.not_mem_nil,
    or_false, List.mem_replicate] at hb
  rcases hb with ((rfl | rfl | rfl | rfl) | ⟨_, rfl⟩) | rfl <;> assumption

/-- A canonical primitive commutes with every expanded Z on a disjoint wire. -/
theorem adjacentClassWord_gate_commute_Z_of_not_mem (a : Gate n) (ha : a.IsAdjacent)
    (i : Fin n) (hi : i ∉ a.support) :
    Commute (adjacentClassWord g [a] (by simpa using ha))
      (adjacentClassWord g (Z (d := d) i) (isAdjacentWord_Z i)) := by
  apply gate_commute_word g a ha _ _
  intro b hb
  have hh : Disjoint a.support (Gate.H i).support := by simpa [Gate.support] using hi
  have hs : Disjoint a.support (Gate.S i).support := by simpa [Gate.support] using hi
  simp only [Z, Sexp, List.mem_append, List.mem_cons, List.not_mem_nil,
    or_false, List.mem_replicate] at hb
  rcases hb with (rfl | rfl | rfl | rfl | rfl) | ⟨_, rfl⟩ <;> assumption

set_option linter.unusedSectionVars false in
private theorem class_push {a b c : Word n} (ha : IsAdjacentWord a)
    (hb : IsAdjacentWord b) (hc : IsAdjacentWord c)
    (h : AdjacentDerives g (a++b) (c++a)) :
    adjacentClassWord g a ha * adjacentClassWord g b hb =
      adjacentClassWord g c hc * adjacentClassWord g a ha := by
  simpa only [adjacentClassWord_append_certified] using
    (adjacentClassWord_eq_iff_derives g _ _ (by simp [ha, hb]) (by simp [hc, ha])).mpr h

private theorem conjugate_mem_of_push {a b c : AdjacentPresentedCircuit g n}
    (h : a*b = c*a) (hc : c ∈ adjacentPresentedPauliSubgroup g) :
    a*b*a⁻¹ ∈ adjacentPresentedPauliSubgroup g := by
  simpa only [h, mul_assoc, mul_inv_cancel, mul_one] using hc

private theorem conjugate_mem_of_commute {a b : AdjacentPresentedCircuit g n}
    (h : Commute a b) (hb : b ∈ adjacentPresentedPauliSubgroup g) :
    a*b*a⁻¹ ∈ adjacentPresentedPauliSubgroup g := conjugate_mem_of_push g h.eq hb

/-- Every adjacent primitive sends each X generator back into the concrete subgroup. -/
theorem gate_conjugate_X_mem_adjacentPresentedPauliSubgroup (a : Gate n) (ha : a.IsAdjacent)
    (i : Fin n) :
    adjacentClassWord g [a] (by simpa using ha) *
      adjacentClassWord g (X (d := d) i) (isAdjacentWord_X i) *
      (adjacentClassWord g [a] (by simpa using ha))⁻¹ ∈ adjacentPresentedPauliSubgroup g := by
  cases a with
  | scalar =>
    exact conjugate_mem_of_commute g
      (adjacentClassWord_gate_commute_X_of_not_mem g .scalar ha i (by simp [Gate.support]))
      (X_mem_adjacentPresentedPauliSubgroup g i)
  | H j =>
    by_cases hji : j = i
    · subst j
      exact conjugate_mem_of_push g
        (class_push g (by simp) (isAdjacentWord_X i) (isAdjacentWord_Z i)
          (adjacentDerives_HX g Fact.out Fact.out i)) (Z_mem_adjacentPresentedPauliSubgroup g i)
    · exact conjugate_mem_of_commute g
        (adjacentClassWord_gate_commute_X_of_not_mem g (.H j) ha i
          (by simpa [Gate.support] using (Ne.symm hji))) (X_mem_adjacentPresentedPauliSubgroup g i)
  | S j =>
    by_cases hji : j = i
    · subst j
      apply conjugate_mem_of_push g
        (class_push g (by simp) (isAdjacentWord_X i) (by simp)
          (adjacentDerives_SX g Fact.out Fact.out i))
      simpa only [adjacentClassWord_append_certified] using
        (adjacentPresentedPauliSubgroup g).mul_mem (X_mem_adjacentPresentedPauliSubgroup g i)
          (Z_mem_adjacentPresentedPauliSubgroup g i)
    · exact conjugate_mem_of_commute g
        (adjacentClassWord_gate_commute_X_of_not_mem g (.S j) ha i
          (by simpa [Gate.support] using (Ne.symm hji))) (X_mem_adjacentPresentedPauliSubgroup g i)
  | CZ j k hjk =>
    by_cases hji : j = i
    · subst j
      apply conjugate_mem_of_push g
        (class_push g (by simpa using ha) (isAdjacentWord_X i) (by simp)
          (adjacentDerives_CZ_X_left g Fact.out Fact.out i k hjk ha))
      simpa only [adjacentClassWord_append_certified] using
        (adjacentPresentedPauliSubgroup g).mul_mem (X_mem_adjacentPresentedPauliSubgroup g i)
          (Z_mem_adjacentPresentedPauliSubgroup g k)
    · by_cases hki : k = i
      · subst k
        apply conjugate_mem_of_push g
          (class_push g (by simpa using ha) (isAdjacentWord_X i) (by simp)
            (adjacentDerives_CZ_X_right g Fact.out Fact.out j i hjk ha))
        simpa only [adjacentClassWord_append_certified] using
          (adjacentPresentedPauliSubgroup g).mul_mem (X_mem_adjacentPresentedPauliSubgroup g i)
            (Z_mem_adjacentPresentedPauliSubgroup g j)
      · exact conjugate_mem_of_commute g
          (adjacentClassWord_gate_commute_X_of_not_mem g (.CZ j k hjk) ha i
            (by simp [Gate.support, Ne.symm hji, Ne.symm hki]))
          (X_mem_adjacentPresentedPauliSubgroup g i)

/-- Every adjacent primitive sends each Z generator back into the concrete subgroup. -/
theorem gate_conjugate_Z_mem_adjacentPresentedPauliSubgroup (a : Gate n) (ha : a.IsAdjacent)
    (i : Fin n) :
    adjacentClassWord g [a] (by simpa using ha) *
      adjacentClassWord g (Z (d := d) i) (isAdjacentWord_Z i) *
      (adjacentClassWord g [a] (by simpa using ha))⁻¹ ∈ adjacentPresentedPauliSubgroup g := by
  cases a with
  | scalar =>
    exact conjugate_mem_of_commute g
      (adjacentClassWord_gate_commute_Z_of_not_mem g .scalar ha i (by simp [Gate.support]))
      (Z_mem_adjacentPresentedPauliSubgroup g i)
  | H j =>
    by_cases hji : j = i
    · subst j
      apply conjugate_mem_of_push g
        (class_push g (by simp) (isAdjacentWord_Z i) ((isAdjacentWord_X i).inverseWord d)
          (adjacentDerives_HZ g Fact.out Fact.out i))
      simpa only [adjacentClassWord_inverseWord] using
        (adjacentPresentedPauliSubgroup g).inv_mem (X_mem_adjacentPresentedPauliSubgroup g i)
    · exact conjugate_mem_of_commute g
        (adjacentClassWord_gate_commute_Z_of_not_mem g (.H j) ha i
          (by simpa [Gate.support] using (Ne.symm hji))) (Z_mem_adjacentPresentedPauliSubgroup g i)
  | S j =>
    by_cases hji : j = i
    · subst j
      exact conjugate_mem_of_push g
        (class_push g (by simp) (isAdjacentWord_Z i) (isAdjacentWord_Z i)
          (adjacentDerives_Z_S_commute g Fact.out Fact.out i).symm)
        (Z_mem_adjacentPresentedPauliSubgroup g i)
    · exact conjugate_mem_of_commute g
        (adjacentClassWord_gate_commute_Z_of_not_mem g (.S j) ha i
          (by simpa [Gate.support] using (Ne.symm hji))) (Z_mem_adjacentPresentedPauliSubgroup g i)
  | CZ j k hjk =>
    by_cases hji : j = i
    · subst j
      exact conjugate_mem_of_push g
        (class_push g (by simpa using ha) (isAdjacentWord_Z i) (isAdjacentWord_Z i)
          (adjacentDerives_CZ_Z_left g Fact.out Fact.out i k hjk ha))
        (Z_mem_adjacentPresentedPauliSubgroup g i)
    · by_cases hki : k = i
      · subst k
        exact conjugate_mem_of_push g
          (class_push g (by simpa using ha) (isAdjacentWord_Z i) (isAdjacentWord_Z i)
            (adjacentDerives_CZ_Z_right g Fact.out Fact.out j i hjk ha))
          (Z_mem_adjacentPresentedPauliSubgroup g i)
      · exact conjugate_mem_of_commute g
          (adjacentClassWord_gate_commute_Z_of_not_mem g (.CZ j k hjk) ha i
            (by simp [Gate.support, Ne.symm hji, Ne.symm hki]))
          (Z_mem_adjacentPresentedPauliSubgroup g i)

/-- Restricted primitive pushing preserves the subgroup generated by the Pauli words. -/
theorem gate_conjugate_mem_adjacentPresentedPauliSubgroup (a : Gate n) (ha : a.IsAdjacent)
    (p : AdjacentPresentedCircuit g n) (hp : p ∈ adjacentPresentedPauliSubgroup g) :
    adjacentClassWord g [a] (by simpa using ha) * p *
      (adjacentClassWord g [a] (by simpa using ha))⁻¹ ∈ adjacentPresentedPauliSubgroup g := by
  induction hp using Subgroup.closure_induction with
  | mem p hp =>
    rcases hp with rfl | ⟨i, rfl | rfl⟩
    · exact conjugate_mem_of_commute g
        (gate_commute g a .scalar ha Gate.isAdjacent_scalar (by simp [Gate.support]))
        (scalar_mem_adjacentPresentedPauliSubgroup g)
    · exact gate_conjugate_X_mem_adjacentPresentedPauliSubgroup g a ha i
    · exact gate_conjugate_Z_mem_adjacentPresentedPauliSubgroup g a ha i
  | one => simpa using (adjacentPresentedPauliSubgroup g (n := n)).one_mem
  | mul p q hp hq ihp ihq =>
    have hmul := (adjacentPresentedPauliSubgroup g).mul_mem ihp ihq
    convert hmul using 1; group
  | inv p hp ih =>
    have hinv := (adjacentPresentedPauliSubgroup g).inv_mem ih
    convert hinv using 1; group

/-- Every adjacent circuit preserves the concrete Pauli subgroup. -/
theorem word_conjugate_mem_adjacentPresentedPauliSubgroup (w : Word n) (hw : IsAdjacentWord w)
    (p : AdjacentPresentedCircuit g n) (hp : p ∈ adjacentPresentedPauliSubgroup g) :
    adjacentClassWord g w hw * p * (adjacentClassWord g w hw)⁻¹ ∈
      adjacentPresentedPauliSubgroup g := by
  induction w with
  | nil => simpa using hp
  | cons a w ih =>
    obtain ⟨ha, hw⟩ := (isAdjacentWord_cons a w).mp hw
    have hm := gate_conjugate_mem_adjacentPresentedPauliSubgroup g a ha _ (ih hw)
    change (pg g a ha * adjacentClassWord g w hw) * p *
      (pg g a ha * adjacentClassWord g w hw)⁻¹ ∈ _
    convert hm using 1; group

/-- Normality of the actual scalar/X/Z-generated subgroup in the source presentation. -/
instance adjacentPresentedPauliSubgroup_normal :
    (adjacentPresentedPauliSubgroup (n := n) g).Normal where
  conj_mem p hp q := by
    obtain ⟨w, hw, rfl⟩ := adjacentClassWord_exists g q
    exact word_conjugate_mem_adjacentPresentedPauliSubgroup g w hw p hp

end QuditClifford.Circuit
