import QuditClifford.GaussSign
import QuditClifford.CircuitSemantics
import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra

/-! # Cyclotomic coefficients and the exact circuit scalar group

Scalar circuits have finite order by a determinant argument, independently of
projective Clifford finiteness. Their entries lie in the actual field Q(omega),
so the cyclotomic roots-of-unity theorem restricts them to powers of -omega.
-/
noncomputable section
namespace QuditClifford
open Matrix
variable (d : ℕ) [NeZero d]

/-- The actual cyclotomic subfield generated by the paper's complex root. -/
def coefficientField : IntermediateField ℚ ℂ := IntermediateField.adjoin ℚ {omega d}

@[simp] theorem omega_mem_coefficientField : omega d ∈ coefficientField d :=
  IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)

/-- Character values are powers of the fixed root and lie in its cyclotomic field. -/
theorem phase_mem_coefficientField (a : ZMod d) : phase d a ∈ coefficientField d := by
  simpa only [← phase_natCast, ZMod.natCast_zmod_val] using
    (coefficientField d).toSubalgebra.pow_mem (omega_mem_coefficientField d) a.val

/-- Integrality identifies adjoining the root as a field or as a rational algebra. -/
theorem coefficientField_toSubalgebra :
    (coefficientField d).toSubalgebra = Algebra.adjoin ℚ {omega d} := by
  apply IntermediateField.adjoin_simple_toSubalgebra_of_integral
  apply IsIntegral.of_pow (NeZero.pos d)
  rw [omega_pow_dimension]
  exact isIntegral_one

instance coefficientField_cyclotomic :
    IsCyclotomicExtension {(⟨d, NeZero.pos d⟩ : ℕ+)} ℚ (coefficientField d) := by
  letI : IsCyclotomicExtension {(⟨d, NeZero.pos d⟩ : ℕ+)} ℚ
      (Algebra.adjoin ℚ ({omega d} : Set ℂ)) :=
    (omega_primitive d).adjoin_isCyclotomicExtension ℚ
  exact IsCyclotomicExtension.equiv {(⟨d, NeZero.pos d⟩ : ℕ+)} ℚ
    (Algebra.adjoin ℚ ({omega d} : Set ℂ))
    (Subalgebra.equivOfEq _ _ (coefficientField_toSubalgebra d).symm)

instance coefficientField_numberField : NumberField (coefficientField d) :=
  IsCyclotomicExtension.numberField {(⟨d, NeZero.pos d⟩ : ℕ+)} ℚ _

/-- The normalized Fourier coefficient is a cyclotomic Gauss sum divided by d. -/
theorem hadamard_scale_eq_gauss_div [Fact d.Prime] (hd : Odd d) :
    (lambda d * (Real.sqrt d : ℂ))⁻¹ = squareGaussSum d (half d) / (d : ℂ) := by
  rw [squareGaussSum_half d hd]
  have hs : (Real.sqrt d : ℂ)^2 = (d : ℂ) := by
    exact_mod_cast Real.sq_sqrt (Nat.cast_nonneg d)
  have hn : (Real.sqrt d : ℂ) ≠ 0 := by
    exact_mod_cast ne_of_gt (Real.sqrt_pos.mpr (Nat.cast_pos.mpr (NeZero.pos d)))
  rw [← hs]
  field_simp [lambda_ne_zero d, hn]
  ring

/-- The Fourier normalization introduces no field extension beyond Q(omega). -/
theorem hadamard_scale_mem_coefficientField [Fact d.Prime] (hd : Odd d) :
    (lambda d * (Real.sqrt d : ℂ))⁻¹ ∈ coefficientField d := by
  rw [hadamard_scale_eq_gauss_div d hd]
  apply (coefficientField d).div_mem
  · exact (coefficientField d).sum_mem (fun a _ => phase_mem_coefficientField d _)
  · exact (coefficientField d).natCast_mem d

/-- All entries of the Fourier generator lie in the cyclotomic field. -/
theorem H_mem_coefficientField [Fact d.Prime] (hd : Odd d) (i j : ZMod d) :
    H d i j ∈ coefficientField d := by
  exact (coefficientField d).mul_mem (hadamard_scale_mem_coefficientField d hd)
    (phase_mem_coefficientField d _)

namespace Circuit
variable {d n : ℕ} [NeZero d]

/-- A common finite exponent for the primitive gates; a deliberately loose
bound suffices to control their determinants. -/
theorem Gate.denote_pow_common (hd : Odd d) (g : Gate n) :
    g.denote d ^ (4*d) = 1 := by
  cases g with
  | scalar =>
    change (scalarGenerator d • (1 : QuditOperator d n)) ^ (4*d) = 1
    rw [smul_pow, one_pow]
    have he : 4*d = (2*d)*2 := by omega
    rw [he, pow_mul, scalarGenerator_pow_twice_dimension, one_pow, one_smul]
  | H i =>
    change onWire i (QuditClifford.H d) ^ (4*d) = 1
    rw [← onWire_pow, pow_mul, H_pow_four d hd, one_pow, onWire_one]
  | S i =>
    change onWire i (QuditClifford.S d) ^ (4*d) = 1
    rw [← onWire_pow, Nat.mul_comm 4 d, pow_mul, S_pow_dimension, one_pow, onWire_one]
  | CZ i j h =>
    have hp : (Gate.CZ i j h).denote d ^ d = 1 := by
      simpa only [denote_replicate, denote_nil] using C6_sound (d := d) i j h
    rw [Nat.mul_comm 4 d, pow_mul, hp, one_pow]

/-- Primitive determinants have a common finite exponent. -/
theorem Gate.det_denote_pow_common (hd : Odd d) (g : Gate n) :
    Matrix.det (g.denote d) ^ (4*d) = 1 := by
  rw [← Matrix.det_pow, g.denote_pow_common hd, Matrix.det_one]

/-- Determinants commute, so every circuit determinant has the same finite
exponent, even though the matrix generators need not commute. -/
theorem det_denote_pow_common (hd : Odd d) (w : Word n) :
    Matrix.det (denote d w) ^ (4*d) = 1 := by
  induction w with
  | nil => simp
  | cons g w ih =>
    rw [denote_cons, Matrix.det_mul, mul_pow, Gate.det_denote_pow_common hd, ih, one_mul]

/-- A scalar primitive circuit has finite multiplicative order, by taking its
determinant in the nonempty computational-basis space. -/
theorem scalar_isOfFinOrder (hd : Odd d) (w : Word n) (c : ℂ)
    (hw : denote d w = c • (1 : QuditOperator d n)) : IsOfFinOrder c := by
  apply isOfFinOrder_iff_pow_eq_one.mpr
  refine ⟨Fintype.card (Pauli.Basis d n) * (4*d), ?_, ?_⟩
  · exact Nat.mul_pos Fintype.card_pos (Nat.mul_pos (by decide) (NeZero.pos d))
  · have hh := det_denote_pow_common hd w
    rw [hw, Matrix.det_smul, Matrix.det_one, mul_one, ← pow_mul] at hh
    exact hh

/-- Each primitive entry lies in Q(omega), including placed Fourier gates. -/
theorem Gate.denote_mem_coefficientField [Fact d.Prime] (hd : Odd d)
    (g : Gate n) (row col : Pauli.Basis d n) : g.denote d row col ∈ coefficientField d := by
  classical
  cases g with
  | scalar =>
    simp only [Gate.denote, Matrix.smul_apply, smul_eq_mul, Matrix.one_apply]
    split_ifs
    · simpa only [mul_one, scalarGenerator] using (coefficientField d).neg_mem (omega_mem_coefficientField d)
    · simp only [mul_zero]; exact (coefficientField d).zero_mem
  | H i =>
    change onWire i (QuditClifford.H d) row col ∈ coefficientField d
    unfold onWire
    split_ifs
    · exact H_mem_coefficientField d hd _ _
    · exact (coefficientField d).zero_mem
  | S i =>
    simp only [Gate.denote, onWire, QuditClifford.S, Matrix.diagonal_apply]
    split_ifs
    · exact phase_mem_coefficientField d _
    all_goals exact (coefficientField d).zero_mem
  | CZ i j h =>
    simp only [Gate.denote, Matrix.diagonal_apply]
    split_ifs
    · exact phase_mem_coefficientField d _
    · exact (coefficientField d).zero_mem

/-- The field of entries is closed under actual circuit matrix multiplication. -/
theorem denote_mem_coefficientField [Fact d.Prime] (hd : Odd d)
    (w : Word n) (row col : Pauli.Basis d n) : denote d w row col ∈ coefficientField d := by
  classical
  induction w generalizing row col with
  | nil =>
    simp only [denote_nil, Matrix.one_apply]
    split_ifs
    · exact (coefficientField d).one_mem
    · exact (coefficientField d).zero_mem
  | cons g w ih =>
    rw [denote_cons, Matrix.mul_apply]
    apply (coefficientField d).sum_mem
    intro mid _
    exact (coefficientField d).mul_mem (g.denote_mem_coefficientField hd row mid) (ih mid col)

/-- A scalar circuit coefficient lies in the actual cyclotomic field. -/
theorem scalar_mem_coefficientField [Fact d.Prime] (hd : Odd d)
    (w : Word n) (c : ℂ) (hw : denote d w = c • (1 : QuditOperator d n)) :
    c ∈ coefficientField d := by
  have hh := denote_mem_coefficientField hd w (0 : Pauli.Basis d n) 0
  simpa only [hw, Matrix.smul_apply, smul_eq_mul, Matrix.one_apply_eq, mul_one] using hh

end Circuit

/-- Roots of unity in the concrete cyclotomic field are powers of the exact
Figure 1 generator -omega. This uses mathlib's cyclotomic classification. -/
theorem coefficientField_torsion_eq_scalarGenerator_pow (hd : Odd d) (c : ℂ)
    (hc : c ∈ coefficientField d) (hfin : IsOfFinOrder c) :
    ∃ r : ℕ, c = scalarGenerator d ^ r := by
  letI : IsCyclotomicExtension {(⟨d, NeZero.pos d⟩ : ℕ+)} ℚ (coefficientField d) :=
    coefficientField_cyclotomic d
  let x : coefficientField d := ⟨c, hc⟩
  let ζ : coefficientField d := ⟨omega d, omega_mem_coefficientField d⟩
  have hζ : IsPrimitiveRoot ζ (⟨d, NeZero.pos d⟩ : ℕ+) := by
    rw [← IsPrimitiveRoot.coe_submonoidClass_iff]
    exact omega_primitive d
  have hx : IsOfFinOrder x := by
    obtain ⟨m, hm, hcm⟩ := isOfFinOrder_iff_pow_eq_one.mp hfin
    refine isOfFinOrder_iff_pow_eq_one.mpr ⟨m, hm, ?_⟩
    exact Subtype.ext hcm
  obtain ⟨r, hr⟩ := IsPrimitiveRoot.exists_neg_pow_of_isOfFinOrder (n := (⟨d, NeZero.pos d⟩ : ℕ+)) hd hζ hx
  refine ⟨r, ?_⟩
  simpa only [x, ζ, scalarGenerator, IntermediateField.coe_pow,
    IntermediateField.coe_neg] using congrArg (fun a : coefficientField d => (a : ℂ)) hr

namespace Circuit
variable {d n : ℕ} [NeZero d] [Fact d.Prime]

/-- Every exact scalar primitive circuit is a power of the specified -omega
generator. The proof combines actual entry closure and a determinant bound. -/
theorem scalar_eq_scalarGenerator_pow (hd : Odd d) (w : Word n) (c : ℂ)
    (hw : denote d w = c • (1 : QuditOperator d n)) :
    ∃ r : ℕ, c = scalarGenerator d ^ r :=
  coefficientField_torsion_eq_scalarGenerator_pow d hd c
    (scalar_mem_coefficientField hd w c hw) (scalar_isOfFinOrder hd w c hw)

/-- In particular every exact circuit scalar has order dividing 2d. -/
theorem scalar_pow_twice_dimension (hd : Odd d) (w : Word n) (c : ℂ)
    (hw : denote d w = c • (1 : QuditOperator d n)) : c ^ (2*d) = 1 := by
  obtain ⟨r, rfl⟩ := scalar_eq_scalarGenerator_pow hd w c hw
  rw [← pow_mul, Nat.mul_comm r, pow_mul, scalarGenerator_pow_twice_dimension, one_pow]

/-- Every scalar circuit has a unique exponent in the canonical range 0..2d-1. -/
theorem scalar_unique_power (hd : Odd d) (w : Word n) (c : ℂ)
    (hw : denote d w = c • (1 : QuditOperator d n)) :
    ∃! r : Fin (2*d), c = scalarGenerator d ^ r.val := by
  have hroot := scalarGenerator_primitive d hd
  obtain ⟨r, hr, hc⟩ := hroot.eq_pow_of_pow_eq_one (scalar_pow_twice_dimension hd w c hw)
  refine ⟨⟨r, hr⟩, hc.symm, ?_⟩
  intro t ht
  apply Fin.ext
  exact hroot.pow_inj t.isLt hr (ht.symm.trans hc.symm)

/-- The exact scalar circuit group is precisely the complex 2d-th roots of unity.
Both the scalar upper bound and realization by powers of -omega are proved. -/
theorem scalar_circuit_iff (hd : Odd d) (c : ℂ) :
    (∃ w : Word n, denote d w = c • (1 : QuditOperator d n)) ↔ c ^ (2*d) = 1 := by
  constructor
  · rintro ⟨w, hw⟩
    exact scalar_pow_twice_dimension hd w c hw
  · intro hc
    obtain ⟨r, _, hr⟩ := (scalarGenerator_primitive d hd).eq_pow_of_pow_eq_one hc
    refine ⟨scalar r, ?_⟩
    rw [denote_scalar, hr]

end Circuit

/-- The source's ring Z[1/d,omega], as an actual subring of the complex numbers. -/
def coefficientRing : Subring ℂ := Subring.closure ({omega d, (d : ℂ)⁻¹} : Set ℂ)

@[simp] theorem omega_mem_coefficientRing : omega d ∈ coefficientRing d :=
  Subring.subset_closure (by simp)

@[simp] theorem inv_dimension_mem_coefficientRing : (d : ℂ)⁻¹ ∈ coefficientRing d :=
  Subring.subset_closure (by simp)

theorem phase_mem_coefficientRing (a : ZMod d) : phase d a ∈ coefficientRing d := by
  simpa only [← phase_natCast, ZMod.natCast_zmod_val] using
    (coefficientRing d).pow_mem (omega_mem_coefficientRing d) a.val

/-- The coefficient ring is contained in the concrete cyclotomic field. -/
theorem coefficientRing_le_field : coefficientRing d ≤ (coefficientField d).toSubring := by
  apply Subring.closure_le.mpr
  intro x hx
  rcases hx with hx | hx
  · simpa only [hx] using omega_mem_coefficientField d
  · simp only [Set.mem_singleton_iff] at hx
    subst x
    exact (coefficientField d).inv_mem ((coefficientField d).natCast_mem d)

/-- Proposition 2.5: the exact Fourier normalization lies in Z[1/d,omega]. -/
theorem hadamard_scale_mem_coefficientRing [Fact d.Prime] (hd : Odd d) :
    (lambda d * (Real.sqrt d : ℂ))⁻¹ ∈ coefficientRing d := by
  rw [hadamard_scale_eq_gauss_div d hd, div_eq_mul_inv]
  exact (coefficientRing d).mul_mem
    ((coefficientRing d).sum_mem (fun a _ => phase_mem_coefficientRing d _))
    (inv_dimension_mem_coefficientRing d)

/-- Proposition 2.6 for the specified exact scalar generator: the finite-order
elements of Z[1/d,omega] are precisely the powers of -omega. -/
theorem coefficientRing_torsion_iff (hd : Odd d) (c : ℂ) :
    (c ∈ coefficientRing d ∧ IsOfFinOrder c) ↔ ∃ r : ℕ, c = scalarGenerator d ^ r := by
  constructor
  · rintro ⟨hc, hfin⟩
    exact coefficientField_torsion_eq_scalarGenerator_pow d hd c
      (coefficientRing_le_field d hc) hfin
  · rintro ⟨r, rfl⟩
    constructor
    · exact (coefficientRing d).pow_mem ((coefficientRing d).neg_mem (omega_mem_coefficientRing d)) r
    · apply isOfFinOrder_iff_pow_eq_one.mpr
      refine ⟨2*d, Nat.mul_pos (by decide) (NeZero.pos d), ?_⟩
      rw [← pow_mul, Nat.mul_comm r, pow_mul, scalarGenerator_pow_twice_dimension, one_pow]

namespace Circuit
variable {d n : ℕ} [NeZero d] [Fact d.Prime]

/-- Every primitive matrix entry belongs to the source's localized cyclotomic ring. -/
theorem Gate.denote_mem_coefficientRing (hd : Odd d)
    (g : Gate n) (row col : Pauli.Basis d n) : g.denote d row col ∈ coefficientRing d := by
  classical
  cases g with
  | scalar =>
    simp only [Gate.denote, Matrix.smul_apply, smul_eq_mul, Matrix.one_apply]
    split_ifs
    · simpa only [mul_one, scalarGenerator] using (coefficientRing d).neg_mem (omega_mem_coefficientRing d)
    · simp only [mul_zero]; exact (coefficientRing d).zero_mem
  | H i =>
    change onWire i (QuditClifford.H d) row col ∈ coefficientRing d
    unfold onWire
    split_ifs
    · exact (coefficientRing d).mul_mem (hadamard_scale_mem_coefficientRing d hd)
        (phase_mem_coefficientRing d _)
    · exact (coefficientRing d).zero_mem
  | S i =>
    simp only [Gate.denote, onWire, QuditClifford.S, Matrix.diagonal_apply]
    split_ifs
    · exact phase_mem_coefficientRing d _
    all_goals exact (coefficientRing d).zero_mem
  | CZ i j h =>
    simp only [Gate.denote, Matrix.diagonal_apply]
    split_ifs
    · exact phase_mem_coefficientRing d _
    · exact (coefficientRing d).zero_mem

/-- Lemma 2.16 for actual primitive words: all circuit entries are in Z[1/d,omega]. -/
theorem denote_mem_coefficientRing (hd : Odd d)
    (w : Word n) (row col : Pauli.Basis d n) : denote d w row col ∈ coefficientRing d := by
  classical
  induction w generalizing row col with
  | nil =>
    simp only [denote_nil, Matrix.one_apply]
    split_ifs
    · exact (coefficientRing d).one_mem
    · exact (coefficientRing d).zero_mem
  | cons g w ih =>
    rw [denote_cons, Matrix.mul_apply]
    apply (coefficientRing d).sum_mem
    intro mid _
    exact (coefficientRing d).mul_mem (g.denote_mem_coefficientRing hd row mid) (ih mid col)

end Circuit

end QuditClifford
