import QuditClifford.CircuitAdjoints
import QuditClifford.PauliCircuit
import QuditClifford.CircuitPauliAction

/-! # The actual Clifford subgroup generated by the paper's primitive gates

This group is a subgroup of complex unitary matrices, defined by generated
closure. In odd dimension its members are precisely denotations of positive
primitive circuit words. It is distinct from both the full unitary normalizer
and the group presented by the rewriting relations.
-/
noncomputable section
namespace QuditClifford.Circuit
open Matrix
variable {d n : ℕ} [NeZero d]

/-- The exact Figure 1 subgroup generated by -omega, H, S, and named-wire CZ. -/
def generatedCliffordGroup (d n : ℕ) [NeZero d] :
    Subgroup (Matrix.unitaryGroup (Pauli.Basis d n) ℂ) :=
  Subgroup.closure (Set.range (fun g : Gate n => unitaryDenote (d := d) [g]))

/-- Every primitive word belongs to the generated matrix subgroup. -/
theorem word_mem_generated (w : Word n) : unitaryDenote (d := d) w ∈ generatedCliffordGroup d n := by
  induction w with
  | nil => exact (generatedCliffordGroup d n).one_mem
  | cons g w ih =>
    change unitaryDenote ([g]++w) ∈ _
    rw [unitaryDenote_append]
    exact (generatedCliffordGroup d n).mul_mem (Subgroup.subset_closure ⟨g, rfl⟩) ih

private def wordSubgroup (hd : Odd d) : Subgroup (Matrix.unitaryGroup (Pauli.Basis d n) ℂ) where
  carrier := Set.range (unitaryDenote (d := d) (n := n))
  one_mem' := ⟨[], rfl⟩
  mul_mem' := by
    rintro _ _ ⟨u, rfl⟩ ⟨v, rfl⟩
    exact ⟨u++v, unitaryDenote_append u v⟩
  inv_mem' := by
    rintro _ ⟨w, rfl⟩
    exact ⟨inverseWord d w, unitaryDenote_inverseWord hd w⟩

/-- Finite gate orders turn generated-group membership into an actual positive word. -/
theorem mem_generated_iff (hd : Odd d) (U : Matrix.unitaryGroup (Pauli.Basis d n) ℂ) :
    U ∈ generatedCliffordGroup d n ↔ ∃ w : Word n, unitaryDenote w = U := by
  have he : generatedCliffordGroup d n = wordSubgroup hd := by
    apply le_antisymm
    · apply (Subgroup.closure_le (wordSubgroup hd)).mpr
      rintro _ ⟨g, rfl⟩
      exact ⟨[g], rfl⟩
    · rintro _ ⟨w, rfl⟩
      exact word_mem_generated w
  rw [he]
  rfl

/-- A word regarded as an element of the actual generated matrix group. -/
def generatedWord (w : Word n) : generatedCliffordGroup d n :=
  ⟨unitaryDenote w, word_mem_generated w⟩

@[simp] theorem generatedWord_nil : generatedWord (d := d) ([] : Word n) = 1 := rfl

@[simp] theorem generatedWord_append (u v : Word n) :
    generatedWord (d := d) (u++v) = generatedWord u * generatedWord v :=
  Subtype.ext (unitaryDenote_append u v)

theorem generatedWord_surjective (hd : Odd d) :
    Function.Surjective (generatedWord (d := d) (n := n)) := by
  intro U
  obtain ⟨w, hw⟩ := (mem_generated_iff hd U.val).mp U.property
  exact ⟨w, Subtype.ext hw⟩

/-- The generated group is contained in the genuine matrix Pauli normalizer. -/
def generatedToNormalizer (hd : Odd d) : generatedCliffordGroup d n →* cliffordMatrixGroup d n where
  toFun U := ⟨U.val, by
    obtain ⟨w, hw⟩ := (mem_generated_iff hd U.val).mp U.property
    change NormalizesPaulis U.val.val
    rw [← hw]
    exact denote_normalizes hd w⟩
  map_one' := rfl
  map_mul' _ _ := rfl

theorem generatedToNormalizer_injective (hd : Odd d) :
    Function.Injective (generatedToNormalizer (d := d) (n := n) hd) := by
  intro U V h
  have hh : U.val = V.val := congrArg (fun W : cliffordMatrixGroup d n => W.val) h
  exact Subtype.ext hh

/-- Actual conjugation action of the generated exact circuit group. -/
def generatedPauliAutHom (hd : Odd d) : generatedCliffordGroup d n →* Pauli.scalarFixingAut d n :=
  normalizerConjugationHom.comp (generatedToNormalizer hd)

/-- The actual generated matrix group acts on the established symplectic space. -/
def generatedSymplecticHom (hd : Odd d) : generatedCliffordGroup d n →* symplecticGroup d n :=
  cliffordSymplecticHom.comp (generatedToNormalizer hd)

@[simp] theorem generatedSymplecticHom_word (hd : Odd d) (w : Word n) (v : PhaseSpace d n) :
    (generatedSymplecticHom hd (generatedWord w)).val v = symplecticAction d w v := by
  exact cliffordSymplecticAction_denote_apply hd w v

/-- The generated group's symplectic kernel is exactly its projective Pauli matrices. -/
theorem mem_generatedSymplecticHom_ker_iff (hd : Odd d) (U : generatedCliffordGroup d n) :
    U ∈ (generatedSymplecticHom hd).ker ↔ ∃ p : Pauli d n, ProjectiveEq U.val.val (Pauli.repr p) :=
  mem_cliffordSymplecticHom_ker_iff (generatedToNormalizer hd U)

/-- Ordinary Paulis are realized by actual primitive words in the generated group. -/
def pauliToGenerated (hd : Odd d) : Pauli d n →* generatedCliffordGroup d n where
  toFun p := generatedWord (pauliWord p)
  map_one' := by
    apply Subtype.ext
    apply Subtype.ext
    change denote d (pauliWord 1) = 1
    rw [denote_pauliWord hd, Pauli.repr_one]
  map_mul' p q := by
    apply Subtype.ext
    apply Subtype.ext
    change denote d (pauliWord (p*q)) = denote d (pauliWord p) * denote d (pauliWord q)
    rw [denote_pauliWord hd, denote_pauliWord hd, denote_pauliWord hd, Pauli.repr_mul]

@[simp] theorem pauliToGenerated_matrix (hd : Odd d) (p : Pauli d n) :
    (pauliToGenerated hd p).val.val = Pauli.repr p := denote_pauliWord hd p

theorem pauliToGenerated_injective (hd : Odd d) :
    Function.Injective (pauliToGenerated (d := d) (n := n) hd) := by
  intro p q h
  apply Pauli.repr_injective
  simpa using congrArg (fun U : generatedCliffordGroup d n => U.val.val) h

/-- Conjugation by a generated matrix is the claimed concrete automorphism. -/
theorem generatedPauliAutHom_matrix (hd : Odd d) (U : generatedCliffordGroup d n)
    (p : Pauli d n) :
    Pauli.repr ((generatedPauliAutHom hd U).val p) =
      U.val.val * Pauli.repr p * U.val.valᴴ :=
  repr_pauliConjugationAut _ _ _ p

/-- The Pauli subgroup realizes precisely the inner Pauli automorphisms. -/
theorem generatedPauliAutHom_pauli (hd : Odd d) (p : Pauli d n) :
    generatedPauliAutHom hd (pauliToGenerated hd p) =
      ⟨MulAut.conj p, Pauli.conj_fixesScalars p⟩ := by
  apply Subtype.ext
  apply MulEquiv.ext
  intro q
  apply Pauli.repr_injective
  rw [generatedPauliAutHom_matrix, pauliToGenerated_matrix, pauli_repr_adjoint hd]
  simp [MulAut.conj_apply, Pauli.repr_mul]

/-- The user's selected enlarged signed Pauli group is a subgroup of generated matrices. -/
def signedPauliToGenerated (hd : Odd d) : SignedPauli d n →* generatedCliffordGroup d n where
  toFun p := generatedWord (signedPauliWord p)
  map_one' := by
    apply Subtype.ext
    apply Subtype.ext
    change denote d (signedPauliWord 1) = 1
    rw [denote_signedPauliWord hd, SignedPauli.repr_one]
  map_mul' p q := by
    apply Subtype.ext
    apply Subtype.ext
    change denote d (signedPauliWord (p*q)) = denote d (signedPauliWord p) * denote d (signedPauliWord q)
    rw [denote_signedPauliWord hd, denote_signedPauliWord hd, denote_signedPauliWord hd,
      SignedPauli.repr_mul]

@[simp] theorem signedPauliToGenerated_matrix (hd : Odd d) (p : SignedPauli d n) :
    (signedPauliToGenerated hd p).val.val = SignedPauli.repr p := denote_signedPauliWord hd p

theorem signedPauliToGenerated_injective (hd : Odd d) :
    Function.Injective (signedPauliToGenerated (d := d) (n := n) hd) := by
  intro p q h
  apply SignedPauli.repr_injective hd
  simpa using congrArg (fun U : generatedCliffordGroup d n => U.val.val) h

end QuditClifford.Circuit
