import QuditClifford.PauliRepresentation

/-!
# A complete exact presentation of the ordinary Pauli subgroup

This supplies the Pauli-normalization part of Sections 3.2 and 4.2 with the
commutator phase retained. It presents the `ω`-phase subgroup, not the enlarged
`-ω` scalar group of Figure 1. The X and Z symbols below denote whole tensor
products of powers, so this is a block presentation, not a claim that the
sixteen Clifford relations have been proved complete.

`Derives` is generated by explicit syntactic equations; semantic equality is
not a generating rule. `complete` proves that these equations suffice.
-/
namespace QuditClifford
namespace PauliRewrite

variable (d n : ℕ)

/-- Formal expressions, not already-normalized Pauli operators. -/
inductive Expr where
  | one
  | phase (c : ZMod d)
  | x (a : Fin n → ZMod d)
  | z (b : Fin n → ZMod d)
  | mul (a b : Expr)
  deriving DecidableEq

namespace Expr
instance : One (Expr d n) := ⟨.one⟩
instance : Mul (Expr d n) := ⟨.mul⟩
end Expr

variable {d n}

/-- The exact Pauli equations, including the nontrivial Weyl phase. -/
inductive Derives : Expr d n → Expr d n → Prop
  | refl (a) : Derives a a
  | symm {a b} : Derives a b → Derives b a
  | trans {a b c} : Derives a b → Derives b c → Derives a c
  | mul {a b c e} : Derives a b → Derives c e → Derives (a*c) (b*e)
  | assoc (a b c) : Derives ((a*b)*c) (a*(b*c))
  | one_mul (a) : Derives (1*a) a
  | mul_one (a) : Derives (a*1) a
  | phase_add (a b) : Derives (Expr.phase a * Expr.phase b) (Expr.phase (a+b))
  | phase_zero : Derives (Expr.phase 0) 1
  | x_add (a b) : Derives (Expr.x a * Expr.x b) (Expr.x (a+b))
  | x_zero : Derives (Expr.x 0) 1
  | z_add (a b) : Derives (Expr.z a * Expr.z b) (Expr.z (a+b))
  | z_zero : Derives (Expr.z 0) 1
  | central (c) (a) : Derives (a * Expr.phase c) (Expr.phase c * a)
  | weyl (b a) : Derives (Expr.z b * Expr.x a)
      (Expr.phase (dot b a) * Expr.x a * Expr.z b)

/-- Interpretation in the finite Heisenberg group. Its connection to matrices
is established separately in `PauliRepresentation`. -/
def eval : Expr d n → Pauli d n
  | .one => 1
  | .phase c => Pauli.scalar c
  | .x a => Pauli.X a
  | .z b => Pauli.Z b
  | .mul a b => eval a * eval b

@[simp] theorem eval_one : eval (1 : Expr d n) = 1 := rfl
@[simp] theorem eval_mul (a b : Expr d n) : eval (a*b) = eval a * eval b := rfl

/-- Every derivation, including its contextual uses, is exact-sound. -/
theorem sound {a b : Expr d n} (h : Derives a b) : eval a = eval b := by
  induction h with
  | refl => rfl
  | symm h ih => exact ih.symm
  | trans h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂
  | mul h₁ h₂ ih₁ ih₂ => simp only [eval_mul, ih₁, ih₂]
  | assoc a b c => exact mul_assoc _ _ _
  | one_mul a => exact one_mul _
  | mul_one a => exact mul_one _
  | phase_add a b => exact (Pauli.scalar_add a b).symm
  | phase_zero => rfl
  | x_add a b => exact (Pauli.X_add a b).symm
  | x_zero => rfl
  | z_add a b => exact (Pauli.Z_add a b).symm
  | z_zero => rfl
  | central c a => exact (Pauli.scalar_commutes c _).symm
  | weyl b a => exact Pauli.Z_mul_X b a

private def setoid (d n : ℕ) : Setoid (Expr d n) where
  r := Derives
  iseqv := ⟨Derives.refl, Derives.symm, Derives.trans⟩

private abbrev Presented (d n : ℕ) := Quotient (setoid d n)

private def cls (a : Expr d n) : Presented d n := Quotient.mk _ a

private instance : One (Presented d n) := ⟨cls 1⟩
private instance : Mul (Presented d n) :=
  ⟨Quotient.map₂ (· * ·) (fun _ _ h₁ _ _ h₂ => Derives.mul h₁ h₂)⟩

private theorem cls_mul (a b : Expr d n) : cls (a*b) = cls a * cls b := rfl

private instance : Monoid (Presented d n) where
  mul_assoc := by
    intro a b c
    induction a using Quotient.inductionOn with | h a =>
      induction b using Quotient.inductionOn with | h b =>
        induction c using Quotient.inductionOn with | h c =>
          exact Quotient.sound (Derives.assoc a b c)
  one_mul := by
    intro a
    induction a using Quotient.inductionOn with | h a =>
      exact Quotient.sound (Derives.one_mul a)
  mul_one := by
    intro a
    induction a using Quotient.inductionOn with | h a =>
      exact Quotient.sound (Derives.mul_one a)

private def P (c : ZMod d) : Presented d n := cls (.phase c)
private def X (a : Fin n → ZMod d) : Presented d n := cls (.x a)
private def Z (b : Fin n → ZMod d) : Presented d n := cls (.z b)

private theorem P_add (a b : ZMod d) : (P a * P b : Presented d n) = P (a+b) :=
  Quotient.sound (Derives.phase_add a b)
private theorem X_add (a b : Fin n → ZMod d) : X a * X b = X (a+b) :=
  Quotient.sound (Derives.x_add a b)
private theorem Z_add (a b : Fin n → ZMod d) : Z a * Z b = Z (a+b) :=
  Quotient.sound (Derives.z_add a b)
private theorem P_zero : (P 0 : Presented d n) = 1 := Quotient.sound Derives.phase_zero
private theorem X_zero : (X 0 : Presented d n) = 1 := Quotient.sound Derives.x_zero
private theorem Z_zero : (Z 0 : Presented d n) = 1 := Quotient.sound Derives.z_zero

private theorem central (c : ZMod d) (a : Presented d n) : a * P c = P c * a := by
  induction a using Quotient.inductionOn with | h a =>
    exact Quotient.sound (Derives.central c a)

private theorem weyl (b a : Fin n → ZMod d) :
    Z b * X a = P (dot b a) * X a * Z b :=
  Quotient.sound (Derives.weyl b a)

/-- The explicit normal expression retains the scalar as well as all exponents. -/
def normal (p : Pauli d n) : Expr d n := .phase p.phase * .x p.x * .z p.z

private def N (p : Pauli d n) : Presented d n := P p.phase * X p.x * Z p.z

private theorem N_mul (p q : Pauli d n) : N p * N q = N (p*q) := by
  dsimp [N]
  calc
    (P p.phase * X p.x * Z p.z) * (P q.phase * X q.x * Z q.z)
        = P p.phase * (X p.x * Z p.z * P q.phase) * X q.x * Z q.z := by simp only [mul_assoc]
    _ = P p.phase * (P q.phase * (X p.x * Z p.z)) * X q.x * Z q.z := by rw [central]
    _ = (P p.phase * P q.phase) * X p.x * (Z p.z * X q.x) * Z q.z := by simp only [mul_assoc]
    _ = P (p.phase + q.phase) * X p.x * (P (dot p.z q.x) * X q.x * Z p.z) * Z q.z := by rw [P_add, weyl]
    _ = P (p.phase + q.phase) * (X p.x * P (dot p.z q.x)) * X q.x * Z p.z * Z q.z := by simp only [mul_assoc]
    _ = P (p.phase + q.phase) * (P (dot p.z q.x) * X p.x) * X q.x * Z p.z * Z q.z := by rw [central]
    _ = (P (p.phase + q.phase) * P (dot p.z q.x)) * (X p.x * X q.x) * (Z p.z * Z q.z) := by simp only [mul_assoc]
    _ = P (p.phase + q.phase + dot p.z q.x) * X (p.x + q.x) * Z (p.z + q.z) := by rw [P_add, X_add, Z_add]

private theorem cls_normal (p : Pauli d n) : cls (normal p) = N p := rfl

private theorem normalize_quotient (a : Expr d n) : cls a = N (eval a) := by
  induction a with
  | one =>
    change (1 : Presented d n) = N 1
    simp [N, P_zero, X_zero, Z_zero]
  | phase c => simp [N, eval, P, X_zero, Z_zero]
  | x a => simp [N, eval, X, P_zero, Z_zero]
  | z b => simp [N, eval, Z, P_zero, X_zero]
  | mul a b iha ihb =>
    rw [show Expr.mul a b = a*b from rfl, cls_mul, iha, ihb, N_mul, eval_mul]

/-- Constructive existence at the level of generated equational derivations. -/
theorem normalize (a : Expr d n) : Derives a (normal (eval a)) := by
  apply @Quotient.exact _ (setoid d n)
  exact (normalize_quotient a).trans (cls_normal _).symm

/-- Exact completeness of the explicit Pauli block relations. -/
theorem complete (a b : Expr d n) (h : eval a = eval b) : Derives a b :=
  (normalize a).trans (h ▸ (normalize b).symm)

theorem derives_iff (a b : Expr d n) : Derives a b ↔ eval a = eval b :=
  ⟨sound, complete a b⟩

/-- For the explicit Pauli block rules, derivability is equivalent to equality
of the actual complex matrices, not merely equality of an abstract model. -/
theorem derives_iff_matrix_eq [NeZero d] (a b : Expr d n) :
    Derives a b ↔ Pauli.repr (eval a) = Pauli.repr (eval b) := by
  rw [derives_iff, Pauli.repr_injective.eq_iff]

end PauliRewrite
end QuditClifford
