import QuditClifford.ControlledXPauliRewrites

/-!
# Normality of the Pauli subgroup in the Figure 1 presentation

This is the subgroup generated by the actual scalar, X, and Z circuit classes.
Its normality follows from syntactic Pauli pushing and structural interchange.
No subgroup is defined as a semantic kernel.
-/

noncomputable section
namespace QuditClifford.Circuit

variable {d n : ℕ} [NeZero d] [Fact d.Prime]
variable (g : (ZMod d)ˣ) [Fact (Odd d)] [Fact (orderOf g = d-1)]

/-- The concrete Pauli generators inside the actual circuit presentation. -/
def presentedPauliGenerators : Set (PresentedCircuit g n) :=
  {q | q = classWord g [.scalar] ∨
    ∃ i, q = classWord g (X (d := d) i) ∨ q = classWord g (Z (d := d) i)}

/-- The subgroup generated by the exact scalar and the expanded Pauli words. -/
def presentedPauliSubgroup : Subgroup (PresentedCircuit g n) :=
  Subgroup.closure (presentedPauliGenerators g)

theorem scalar_mem_presentedPauliSubgroup :
    classWord (n := n) g [.scalar] ∈ presentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inl rfl)

theorem X_mem_presentedPauliSubgroup (i : Fin n) :
    classWord g (X (d := d) i) ∈ presentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inr ⟨i, Or.inl rfl⟩)

theorem Z_mem_presentedPauliSubgroup (i : Fin n) :
    classWord g (Z (d := d) i) ∈ presentedPauliSubgroup g :=
  Subgroup.subset_closure (Or.inr ⟨i, Or.inr rfl⟩)

theorem scalarWord_mem_presentedPauliSubgroup (k : ℕ) :
    classWord (n := n) g (scalar k) ∈ presentedPauliSubgroup g := by
  rw [scalar, classWord_replicate]
  exact (presentedPauliSubgroup g).pow_mem (scalar_mem_presentedPauliSubgroup g) k

theorem omegaPower_mem_presentedPauliSubgroup (a : ZMod d) :
    classWord (n := n) g (omegaPower a) ∈ presentedPauliSubgroup g :=
  scalarWord_mem_presentedPauliSubgroup g _

private theorem flatten_mem_presentedPauliSubgroup (ws : List (Word n))
    (h : ∀ w ∈ ws, classWord g w ∈ presentedPauliSubgroup g) :
    classWord g ws.flatten ∈ presentedPauliSubgroup g := by
  induction ws with
  | nil => exact (presentedPauliSubgroup g).one_mem
  | cons w ws ih =>
      rw [List.flatten_cons, classWord_append]
      exact (presentedPauliSubgroup g).mul_mem (h w (by simp))
        (ih (fun u hu => h u (by simp [hu])))

theorem allX_mem_presentedPauliSubgroup (x : Pauli.Basis d n) :
    classWord g (allX x) ∈ presentedPauliSubgroup g := by
  apply flatten_mem_presentedPauliSubgroup
  intro w hw
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hw
  rw [Xexp, classWord_power]
  exact (presentedPauliSubgroup g).pow_mem (X_mem_presentedPauliSubgroup g i) _

theorem allZ_mem_presentedPauliSubgroup (z : Pauli.Basis d n) :
    classWord g (allZ z) ∈ presentedPauliSubgroup g := by
  apply flatten_mem_presentedPauliSubgroup
  intro w hw
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hw
  rw [Zexp, classWord_power]
  exact (presentedPauliSubgroup g).pow_mem (Z_mem_presentedPauliSubgroup g i) _

theorem pauliWord_mem_presentedPauliSubgroup (p : Pauli d n) :
    classWord g (pauliWord p) ∈ presentedPauliSubgroup g := by
  rw [pauliWord, classWord_append, classWord_append]
  exact (presentedPauliSubgroup g).mul_mem
    ((presentedPauliSubgroup g).mul_mem (omegaPower_mem_presentedPauliSubgroup g p.phase)
      (allX_mem_presentedPauliSubgroup g p.x)) (allZ_mem_presentedPauliSubgroup g p.z)

theorem signedPauliWord_mem_presentedPauliSubgroup (p : SignedPauli d n) :
    classWord g (signedPauliWord p) ∈ presentedPauliSubgroup g := by
  rw [signedPauliWord, classWord_append]
  exact (presentedPauliSubgroup g).mul_mem (scalarWord_mem_presentedPauliSubgroup g _)
    (pauliWord_mem_presentedPauliSubgroup g p.2)

set_option linter.unusedSectionVars false in
private theorem gate_commute (a b : Gate n) (h : Disjoint a.support b.support) :
    Commute (classWord g [a]) (classWord g [b]) :=
  (classWord_eq_iff_derives g _ _).mpr (.rule (Or.inl (Structural.disjoint a b h)))

/-- Structural interchange extends to an expanded off-wire X word. -/
theorem classWord_gate_commute_X_of_not_mem (a : Gate n) (i : Fin n)
    (hi : i ∉ a.support) : Commute (classWord g [a]) (classWord g (X (d := d) i)) := by
  have hh := gate_commute g a (.H i) (by simpa [Gate.support] using hi)
  have hs := gate_commute g a (.S i) (by simpa [Gate.support] using hi)
  rw [classWord_X_expand]
  exact (((hh.mul_right hs).mul_right (hh.pow_right 2)).mul_right hs.inv_right).mul_right hh

/-- Structural interchange extends to an expanded off-wire Z word. -/
theorem classWord_gate_commute_Z_of_not_mem (a : Gate n) (i : Fin n)
    (hi : i ∉ a.support) : Commute (classWord g [a]) (classWord g (Z (d := d) i)) := by
  have hh := gate_commute g a (.H i) (by simpa [Gate.support] using hi)
  have hs := gate_commute g a (.S i) (by simpa [Gate.support] using hi)
  rw [classWord_Z_expand]
  exact (((hh.pow_right 2).mul_right hs).mul_right (hh.pow_right 2)).mul_right hs.inv_right

private theorem conjugate_mem_of_push {a b c : PresentedCircuit g n}
    (h : a*b = c*a) (hc : c ∈ presentedPauliSubgroup g) :
    a*b*a⁻¹ ∈ presentedPauliSubgroup g := by
  simpa only [h, mul_assoc, mul_inv_cancel, mul_one] using hc

private theorem conjugate_mem_of_commute {a b : PresentedCircuit g n}
    (h : Commute a b) (hb : b ∈ presentedPauliSubgroup g) :
    a*b*a⁻¹ ∈ presentedPauliSubgroup g :=
  conjugate_mem_of_push g h.eq hb

theorem gate_conjugate_X_mem_presentedPauliSubgroup (a : Gate n) (i : Fin n) :
    classWord g [a] * classWord g (X (d := d) i) * (classWord g [a])⁻¹ ∈
      presentedPauliSubgroup g := by
  cases a with
  | scalar =>
      exact conjugate_mem_of_commute g
        (classWord_gate_commute_X_of_not_mem g .scalar i (by simp [Gate.support]))
        (X_mem_presentedPauliSubgroup g i)
  | H j =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_push g (classWord_HX_eq_ZH g i)
          (Z_mem_presentedPauliSubgroup g i)
      · exact conjugate_mem_of_commute g
          (classWord_gate_commute_X_of_not_mem g (.H j) i (by simpa [Gate.support] using (Ne.symm hji)))
          (X_mem_presentedPauliSubgroup g i)
  | S j =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_push g (classWord_SX g i)
          ((presentedPauliSubgroup g).mul_mem (X_mem_presentedPauliSubgroup g i)
            (Z_mem_presentedPauliSubgroup g i))
      · exact conjugate_mem_of_commute g
          (classWord_gate_commute_X_of_not_mem g (.S j) i (by simpa [Gate.support] using (Ne.symm hji)))
          (X_mem_presentedPauliSubgroup g i)
  | CZ j k hjk =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_push g (classWord_CZ_X_left g i k hjk)
          ((presentedPauliSubgroup g).mul_mem (X_mem_presentedPauliSubgroup g i)
            (Z_mem_presentedPauliSubgroup g k))
      · by_cases hki : k = i
        · subst k
          exact conjugate_mem_of_push g (classWord_CZ_X_right g j i hjk)
            ((presentedPauliSubgroup g).mul_mem (X_mem_presentedPauliSubgroup g i)
              (Z_mem_presentedPauliSubgroup g j))
        · exact conjugate_mem_of_commute g
            (classWord_gate_commute_X_of_not_mem g (.CZ j k hjk) i
              (by simp [Gate.support, (Ne.symm hji), (Ne.symm hki)]))
            (X_mem_presentedPauliSubgroup g i)

theorem gate_conjugate_Z_mem_presentedPauliSubgroup (a : Gate n) (i : Fin n) :
    classWord g [a] * classWord g (Z (d := d) i) * (classWord g [a])⁻¹ ∈
      presentedPauliSubgroup g := by
  cases a with
  | scalar =>
      exact conjugate_mem_of_commute g
        (classWord_gate_commute_Z_of_not_mem g .scalar i (by simp [Gate.support]))
        (Z_mem_presentedPauliSubgroup g i)
  | H j =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_push g (classWord_HZ g i)
          ((presentedPauliSubgroup g).inv_mem (X_mem_presentedPauliSubgroup g i))
      · exact conjugate_mem_of_commute g
          (classWord_gate_commute_Z_of_not_mem g (.H j) i (by simpa [Gate.support] using (Ne.symm hji)))
          (Z_mem_presentedPauliSubgroup g i)
  | S j =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_commute g (classWord_Z_commute_S g i).symm
          (Z_mem_presentedPauliSubgroup g i)
      · exact conjugate_mem_of_commute g
          (classWord_gate_commute_Z_of_not_mem g (.S j) i (by simpa [Gate.support] using (Ne.symm hji)))
          (Z_mem_presentedPauliSubgroup g i)
  | CZ j k hjk =>
      by_cases hji : j = i
      · subst j
        exact conjugate_mem_of_commute g (classWord_CZ_commute_Z_left g i k hjk)
          (Z_mem_presentedPauliSubgroup g i)
      · by_cases hki : k = i
        · subst k
          exact conjugate_mem_of_commute g (classWord_CZ_commute_Z_right g j i hjk)
            (Z_mem_presentedPauliSubgroup g i)
        · exact conjugate_mem_of_commute g
            (classWord_gate_commute_Z_of_not_mem g (.CZ j k hjk) i
              (by simp [Gate.support, (Ne.symm hji), (Ne.symm hki)]))
            (Z_mem_presentedPauliSubgroup g i)

/-- Each primitive gate preserves the subgroup generated by scalar, X, and Z. -/
theorem gate_conjugate_mem_presentedPauliSubgroup (a : Gate n)
    (p : PresentedCircuit g n) (hp : p ∈ presentedPauliSubgroup g) :
    classWord g [a] * p * (classWord g [a])⁻¹ ∈ presentedPauliSubgroup g := by
  induction hp using Subgroup.closure_induction with
  | mem p hp =>
      rcases hp with rfl | ⟨i, rfl | rfl⟩
      · exact conjugate_mem_of_commute g
          (gate_commute g a .scalar (by simp [Gate.support]))
          (scalar_mem_presentedPauliSubgroup g)
      · exact gate_conjugate_X_mem_presentedPauliSubgroup g a i
      · exact gate_conjugate_Z_mem_presentedPauliSubgroup g a i
  | one => simpa using (presentedPauliSubgroup g (n := n)).one_mem
  | mul p q hp hq ihp ihq =>
      have hmul := (presentedPauliSubgroup g).mul_mem ihp ihq
      convert hmul using 1; group
  | inv p hp ih =>
      have hinv := (presentedPauliSubgroup g).inv_mem ih
      convert hinv using 1; group

/-- Every circuit preserves this concrete Pauli subgroup by syntactic pushing. -/
theorem word_conjugate_mem_presentedPauliSubgroup (w : Word n)
    (p : PresentedCircuit g n) (hp : p ∈ presentedPauliSubgroup g) :
    classWord g w * p * (classWord g w)⁻¹ ∈ presentedPauliSubgroup g := by
  induction w with
  | nil => simpa using hp
  | cons a w ih =>
      have hm := gate_conjugate_mem_presentedPauliSubgroup g a _ ih
      rw [classWord_cons]
      convert hm using 1; group

/-- The actual subgroup generated by the Pauli circuit words is normal. -/
instance presentedPauliSubgroup_normal : (presentedPauliSubgroup (n := n) g).Normal where
  conj_mem p hp q := by
    obtain ⟨w, rfl⟩ := classWord_surjective g q
    exact word_conjugate_mem_presentedPauliSubgroup g w p hp

end QuditClifford.Circuit
